// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type AuditLog struct {
	ID           int64
	OccurredAt   string
	Action       string
	Status       string
	Subject      string
	Destination  string
	Details      string
	ErrorMessage string
}

type DumpFile struct {
	ID           int64
	RelativePath string
	ItemKey      string
	FileName     string
	Sha256       string
	SizeBytes    int64
	Encrypted    int64
	EncID        string
	CreatedAt    string
}

type RestoreHistory struct {
	ID               int64
	DumpID           sql.NullInt64
	DumpRelativePath string
	DumpSha256       string
	DestinationKey   string
	RestoredAt       string
	DurationMs       int64
	Status           string
	CleanRestore     int64
	Warnings         string
	ErrorMessage     string
}

type Secret struct {
	Key        string
	Ciphertext string
	CreatedAt  string
	UpdatedAt  string
	LastUsedAt sql.NullString
}

type SecretRotation struct {
	ID        int64
	SecretKey string
	Action    string
	RotatedAt string
}

type VaultMetum struct {
	ID                 int64
	MasterPasswordHash sql.NullString
	KdfSalt            sql.NullString
	EncID              sql.NullString
	S3SecretKey        sql.NullString
	CreatedAt          string
	UpdatedAt          string
}
