// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: secrets.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secrets WHERE key = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, key)
	return err
}

const getSecretCiphertext = `-- name: GetSecretCiphertext :one
SELECT ciphertext FROM secrets WHERE key = ?
`

func (q *Queries) GetSecretCiphertext(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSecretCiphertext, key)
	var ciphertext string
	err := row.Scan(&ciphertext)
	return ciphertext, err
}

const insertSecret = `-- name: InsertSecret :exec
INSERT INTO secrets (key, ciphertext, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type InsertSecretParams struct {
	Key        string
	Ciphertext string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) error {
	_, err := q.db.ExecContext(ctx, insertSecret,
		arg.Key,
		arg.Ciphertext,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertSecretRotation = `-- name: InsertSecretRotation :exec
INSERT INTO secret_rotations (secret_key, action, rotated_at)
VALUES (?, ?, ?)
`

type InsertSecretRotationParams struct {
	SecretKey string
	Action    string
	RotatedAt string
}

func (q *Queries) InsertSecretRotation(ctx context.Context, arg InsertSecretRotationParams) error {
	_, err := q.db.ExecContext(ctx, insertSecretRotation, arg.SecretKey, arg.Action, arg.RotatedAt)
	return err
}

const listAllSecretCiphertexts = `-- name: ListAllSecretCiphertexts :many
SELECT key, ciphertext FROM secrets
`

type ListAllSecretCiphertextsRow struct {
	Key        string
	Ciphertext string
}

func (q *Queries) ListAllSecretCiphertexts(ctx context.Context) ([]ListAllSecretCiphertextsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllSecretCiphertexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSecretCiphertextsRow{}
	for rows.Next() {
		var i ListAllSecretCiphertextsRow
		if err := rows.Scan(&i.Key, &i.Ciphertext); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretRotations = `-- name: ListSecretRotations :many
SELECT id, secret_key, action, rotated_at
FROM secret_rotations
WHERE secret_key = ?
ORDER BY rotated_at DESC
LIMIT ?
`

type ListSecretRotationsParams struct {
	SecretKey string
	Limit     int64
}

func (q *Queries) ListSecretRotations(ctx context.Context, arg ListSecretRotationsParams) ([]SecretRotation, error) {
	rows, err := q.db.QueryContext(ctx, listSecretRotations, arg.SecretKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecretRotation{}
	for rows.Next() {
		var i SecretRotation
		if err := rows.Scan(
			&i.ID,
			&i.SecretKey,
			&i.Action,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT key, created_at, updated_at, last_used_at
FROM secrets
ORDER BY key
`

type ListSecretsRow struct {
	Key        string
	CreatedAt  string
	UpdatedAt  string
	LastUsedAt sql.NullString
}

func (q *Queries) ListSecrets(ctx context.Context) ([]ListSecretsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSecretsRow{}
	for rows.Next() {
		var i ListSecretsRow
		if err := rows.Scan(
			&i.Key,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const secretExists = `-- name: SecretExists :one
SELECT 1 AS exists_flag FROM secrets WHERE key = ? LIMIT 1
`

func (q *Queries) SecretExists(ctx context.Context, key string) (int64, error) {
	row := q.db.QueryRowContext(ctx, secretExists, key)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const touchSecretUsed = `-- name: TouchSecretUsed :exec
UPDATE secrets SET last_used_at = ? WHERE key = ?
`

type TouchSecretUsedParams struct {
	LastUsedAt sql.NullString
	Key        string
}

func (q *Queries) TouchSecretUsed(ctx context.Context, arg TouchSecretUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchSecretUsed, arg.LastUsedAt, arg.Key)
	return err
}

const updateSecret = `-- name: UpdateSecret :exec
UPDATE secrets SET ciphertext = ?, updated_at = ? WHERE key = ?
`

type UpdateSecretParams struct {
	Ciphertext string
	UpdatedAt  string
	Key        string
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) error {
	_, err := q.db.ExecContext(ctx, updateSecret, arg.Ciphertext, arg.UpdatedAt, arg.Key)
	return err
}

const updateSecretCiphertext = `-- name: UpdateSecretCiphertext :exec
UPDATE secrets SET ciphertext = ?, updated_at = ? WHERE key = ?
`

type UpdateSecretCiphertextParams struct {
	Ciphertext string
	UpdatedAt  string
	Key        string
}

func (q *Queries) UpdateSecretCiphertext(ctx context.Context, arg UpdateSecretCiphertextParams) error {
	_, err := q.db.ExecContext(ctx, updateSecretCiphertext, arg.Ciphertext, arg.UpdatedAt, arg.Key)
	return err
}
