// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package sqlcgen

import (
	"context"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (
  occurred_at, action, status, subject, destination, details, error_message
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertAuditLogParams struct {
	OccurredAt   string
	Action       string
	Status       string
	Subject      string
	Destination  string
	Details      string
	ErrorMessage string
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, insertAuditLog,
		arg.OccurredAt,
		arg.Action,
		arg.Status,
		arg.Subject,
		arg.Destination,
		arg.Details,
		arg.ErrorMessage,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, occurred_at, action, status, subject, destination, details, error_message
FROM audit_log
ORDER BY occurred_at DESC
LIMIT ?
`

func (q *Queries) ListAuditLog(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Action,
			&i.Status,
			&i.Subject,
			&i.Destination,
			&i.Details,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByAction = `-- name: ListAuditLogByAction :many
SELECT id, occurred_at, action, status, subject, destination, details, error_message
FROM audit_log
WHERE action = ?
ORDER BY occurred_at DESC
LIMIT ?
`

type ListAuditLogByActionParams struct {
	Action string
	Limit  int64
}

func (q *Queries) ListAuditLogByAction(ctx context.Context, arg ListAuditLogByActionParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogByAction, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Action,
			&i.Status,
			&i.Subject,
			&i.Destination,
			&i.Details,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
