// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dumps.sql

package sqlcgen

import (
	"context"
)

const getDumpByPath = `-- name: GetDumpByPath :one
SELECT id, relative_path, item_key, file_name, sha256, size_bytes, encrypted, enc_id, created_at
FROM dump_files
WHERE relative_path = ?
`

func (q *Queries) GetDumpByPath(ctx context.Context, relativePath string) (DumpFile, error) {
	row := q.db.QueryRowContext(ctx, getDumpByPath, relativePath)
	var i DumpFile
	err := row.Scan(
		&i.ID,
		&i.RelativePath,
		&i.ItemKey,
		&i.FileName,
		&i.Sha256,
		&i.SizeBytes,
		&i.Encrypted,
		&i.EncID,
		&i.CreatedAt,
	)
	return i, err
}

const listDumps = `-- name: ListDumps :many
SELECT id, relative_path, item_key, file_name, sha256, size_bytes, encrypted, enc_id, created_at
FROM dump_files
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListDumps(ctx context.Context, limit int64) ([]DumpFile, error) {
	rows, err := q.db.QueryContext(ctx, listDumps, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DumpFile{}
	for rows.Next() {
		var i DumpFile
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.ItemKey,
			&i.FileName,
			&i.Sha256,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDumpsByItemKey = `-- name: ListDumpsByItemKey :many
SELECT id, relative_path, item_key, file_name, sha256, size_bytes, encrypted, enc_id, created_at
FROM dump_files
WHERE item_key = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListDumpsByItemKeyParams struct {
	ItemKey string
	Limit   int64
}

func (q *Queries) ListDumpsByItemKey(ctx context.Context, arg ListDumpsByItemKeyParams) ([]DumpFile, error) {
	rows, err := q.db.QueryContext(ctx, listDumpsByItemKey, arg.ItemKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DumpFile{}
	for rows.Next() {
		var i DumpFile
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.ItemKey,
			&i.FileName,
			&i.Sha256,
			&i.SizeBytes,
			&i.Encrypted,
			&i.EncID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDumpFile = `-- name: UpsertDumpFile :exec
INSERT INTO dump_files (
  relative_path, item_key, file_name, sha256, size_bytes, encrypted, enc_id, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(relative_path) DO UPDATE SET
  sha256 = excluded.sha256,
  size_bytes = excluded.size_bytes,
  encrypted = excluded.encrypted,
  enc_id = excluded.enc_id
`

type UpsertDumpFileParams struct {
	RelativePath string
	ItemKey      string
	FileName     string
	Sha256       string
	SizeBytes    int64
	Encrypted    int64
	EncID        string
	CreatedAt    string
}

func (q *Queries) UpsertDumpFile(ctx context.Context, arg UpsertDumpFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertDumpFile,
		arg.RelativePath,
		arg.ItemKey,
		arg.FileName,
		arg.Sha256,
		arg.SizeBytes,
		arg.Encrypted,
		arg.EncID,
		arg.CreatedAt,
	)
	return err
}
