// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: restore.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const insertRestoreHistory = `-- name: InsertRestoreHistory :exec
INSERT INTO restore_history (
  dump_id, dump_relative_path, dump_sha256, destination_key, restored_at,
  duration_ms, status, clean_restore, warnings, error_message
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRestoreHistoryParams struct {
	DumpID           sql.NullInt64
	DumpRelativePath string
	DumpSha256       string
	DestinationKey   string
	RestoredAt       string
	DurationMs       int64
	Status           string
	CleanRestore     int64
	Warnings         string
	ErrorMessage     string
}

func (q *Queries) InsertRestoreHistory(ctx context.Context, arg InsertRestoreHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertRestoreHistory,
		arg.DumpID,
		arg.DumpRelativePath,
		arg.DumpSha256,
		arg.DestinationKey,
		arg.RestoredAt,
		arg.DurationMs,
		arg.Status,
		arg.CleanRestore,
		arg.Warnings,
		arg.ErrorMessage,
	)
	return err
}

const listRestoreHistory = `-- name: ListRestoreHistory :many
SELECT id, dump_id, dump_relative_path, dump_sha256, destination_key, restored_at,
  duration_ms, status, clean_restore, warnings, error_message
FROM restore_history
ORDER BY restored_at DESC
LIMIT ?
`

func (q *Queries) ListRestoreHistory(ctx context.Context, limit int64) ([]RestoreHistory, error) {
	rows, err := q.db.QueryContext(ctx, listRestoreHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestoreHistory{}
	for rows.Next() {
		var i RestoreHistory
		if err := rows.Scan(
			&i.ID,
			&i.DumpID,
			&i.DumpRelativePath,
			&i.DumpSha256,
			&i.DestinationKey,
			&i.RestoredAt,
			&i.DurationMs,
			&i.Status,
			&i.CleanRestore,
			&i.Warnings,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestoreHistoryByDestination = `-- name: ListRestoreHistoryByDestination :many
SELECT id, dump_id, dump_relative_path, dump_sha256, destination_key, restored_at,
  duration_ms, status, clean_restore, warnings, error_message
FROM restore_history
WHERE destination_key = ?
ORDER BY restored_at DESC
LIMIT ?
`

type ListRestoreHistoryByDestinationParams struct {
	DestinationKey string
	Limit          int64
}

func (q *Queries) ListRestoreHistoryByDestination(ctx context.Context, arg ListRestoreHistoryByDestinationParams) ([]RestoreHistory, error) {
	rows, err := q.db.QueryContext(ctx, listRestoreHistoryByDestination, arg.DestinationKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RestoreHistory{}
	for rows.Next() {
		var i RestoreHistory
		if err := rows.Scan(
			&i.ID,
			&i.DumpID,
			&i.DumpRelativePath,
			&i.DumpSha256,
			&i.DestinationKey,
			&i.RestoredAt,
			&i.DurationMs,
			&i.Status,
			&i.CleanRestore,
			&i.Warnings,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
