// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vault_meta.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*) FROM audit_log
`

func (q *Queries) CountAuditLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDumpFiles = `-- name: CountDumpFiles :one
SELECT COUNT(*) FROM dump_files
`

func (q *Queries) CountDumpFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDumpFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRestoreHistory = `-- name: CountRestoreHistory :one
SELECT COUNT(*) FROM restore_history
`

func (q *Queries) CountRestoreHistory(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRestoreHistory)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecrets = `-- name: CountSecrets :one
SELECT COUNT(*) FROM secrets
`

func (q *Queries) CountSecrets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecrets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVaultCreatedAt = `-- name: GetVaultCreatedAt :one
SELECT created_at FROM vault_meta WHERE id = 1
`

func (q *Queries) GetVaultCreatedAt(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getVaultCreatedAt)
	var created_at string
	err := row.Scan(&created_at)
	return created_at, err
}

const getVaultEncID = `-- name: GetVaultEncID :one
SELECT enc_id FROM vault_meta WHERE id = 1
`

func (q *Queries) GetVaultEncID(ctx context.Context) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getVaultEncID)
	var enc_id sql.NullString
	err := row.Scan(&enc_id)
	return enc_id, err
}

const getVaultMasterFields = `-- name: GetVaultMasterFields :one
SELECT master_password_hash, kdf_salt
FROM vault_meta WHERE id = 1
`

type GetVaultMasterFieldsRow struct {
	MasterPasswordHash sql.NullString
	KdfSalt            sql.NullString
}

func (q *Queries) GetVaultMasterFields(ctx context.Context) (GetVaultMasterFieldsRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultMasterFields)
	var i GetVaultMasterFieldsRow
	err := row.Scan(&i.MasterPasswordHash, &i.KdfSalt)
	return i, err
}

const getVaultMetaRow = `-- name: GetVaultMetaRow :one
SELECT master_password_hash, kdf_salt, enc_id, s3_secret_key
FROM vault_meta WHERE id = 1
`

type GetVaultMetaRowRow struct {
	MasterPasswordHash sql.NullString
	KdfSalt            sql.NullString
	EncID              sql.NullString
	S3SecretKey        sql.NullString
}

func (q *Queries) GetVaultMetaRow(ctx context.Context) (GetVaultMetaRowRow, error) {
	row := q.db.QueryRowContext(ctx, getVaultMetaRow)
	var i GetVaultMetaRowRow
	err := row.Scan(
		&i.MasterPasswordHash,
		&i.KdfSalt,
		&i.EncID,
		&i.S3SecretKey,
	)
	return i, err
}

const insertVaultMeta = `-- name: InsertVaultMeta :exec
INSERT INTO vault_meta (id, created_at, updated_at) VALUES (1, ?, ?)
`

type InsertVaultMetaParams struct {
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) InsertVaultMeta(ctx context.Context, arg InsertVaultMetaParams) error {
	_, err := q.db.ExecContext(ctx, insertVaultMeta, arg.CreatedAt, arg.UpdatedAt)
	return err
}

const setVaultEncID = `-- name: SetVaultEncID :exec
UPDATE vault_meta SET enc_id = ?, updated_at = ? WHERE id = 1
`

type SetVaultEncIDParams struct {
	EncID     sql.NullString
	UpdatedAt string
}

func (q *Queries) SetVaultEncID(ctx context.Context, arg SetVaultEncIDParams) error {
	_, err := q.db.ExecContext(ctx, setVaultEncID, arg.EncID, arg.UpdatedAt)
	return err
}

const setVaultMeta = `-- name: SetVaultMeta :exec
UPDATE vault_meta
SET master_password_hash = ?, kdf_salt = ?, enc_id = ?, s3_secret_key = ?, updated_at = ?
WHERE id = 1
`

type SetVaultMetaParams struct {
	MasterPasswordHash sql.NullString
	KdfSalt            sql.NullString
	EncID              sql.NullString
	S3SecretKey        sql.NullString
	UpdatedAt          string
}

func (q *Queries) SetVaultMeta(ctx context.Context, arg SetVaultMetaParams) error {
	_, err := q.db.ExecContext(ctx, setVaultMeta,
		arg.MasterPasswordHash,
		arg.KdfSalt,
		arg.EncID,
		arg.S3SecretKey,
		arg.UpdatedAt,
	)
	return err
}

const setVaultS3SecretKey = `-- name: SetVaultS3SecretKey :exec
UPDATE vault_meta SET s3_secret_key = ?, updated_at = ? WHERE id = 1
`

type SetVaultS3SecretKeyParams struct {
	S3SecretKey sql.NullString
	UpdatedAt   string
}

func (q *Queries) SetVaultS3SecretKey(ctx context.Context, arg SetVaultS3SecretKeyParams) error {
	_, err := q.db.ExecContext(ctx, setVaultS3SecretKey, arg.S3SecretKey, arg.UpdatedAt)
	return err
}

const touchVaultMeta = `-- name: TouchVaultMeta :exec
UPDATE vault_meta SET updated_at = ? WHERE id = 1
`

func (q *Queries) TouchVaultMeta(ctx context.Context, updatedAt string) error {
	_, err := q.db.ExecContext(ctx, touchVaultMeta, updatedAt)
	return err
}

const vaultMetaRowExists = `-- name: VaultMetaRowExists :one
SELECT CAST(COALESCE((SELECT 1 FROM vault_meta WHERE id = 1), 0) AS INTEGER) AS exists_flag
`

func (q *Queries) VaultMetaRowExists(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, vaultMetaRowExists)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}
